services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    depends_on:
      - php

  php:
    build: ./images/php
    volumes:
      - ./www:/var/www
    depends_on:
      - db

  db:
    build: ./db
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret